sonar.projectKey=dummy-node-app
sonar.projectName=dummy-node-app
sonar.sources=.
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**,environment/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
